### DISCUSSION TITLE
@font-face not working, Is this bug or just my mistake?

### DISCUSSION THREAD

**Discussion by argxentakato** [react-static/react-static#1490] [General] [answered]
I used the following code in CSS but the fonts never changed.

* style.css
```css
@font-face {
    font-family: "PixelMplus12";
    src: url("./fonts/PixelMplus12-Regular.woff2") format("woff2");
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: "PixelMplus12";
    src: url("./fonts/PixelMplus12-Bold.woff2") format("woff2");
    font-weight: bold;
    font-style: normal;
}

html, body {
    font-family: "PixelMplus12" !important;
    font-size: 12px;
    color: #222222;
}
```

* App.js
```jsx
import React, { Component } from 'react'
import {Helmet} from 'react-helmet'

import "./style.css"

class App extends Component {
  render() {
    return (
      <div>
        <Helmet>
          <title>銀猫さんのWebサイト</title>
        </Helmet>
        <h1>Hello world</h1>
      </div>
    )
  }
}

export default App
```
