### ISSUE TITLE
[Bug] After using assetsPath to configure build, the url reference address in less is wrong

### ISSUE THREAD

**Issue by chinacoolboyzz** [react-static/react-static#1477]
react-static: "^7.2.0"

```js
// static.config.js
export default {
  plugins: [
    require.resolve("react-static-plugin-less")
    ...
  ],
  assetsPath: "https://xxx.xxx.com/dir/",
  ...
};
```
```less
// app.less
@font-face {
  font-family: "my-number";
  src: url('./assets/number.ttf');
}
```
### Expected Behavior

The correct situation should be assetsPath + filePath splicing.
url: https://xxx.xxx.com/dir/static/number.ttf

### Reproducible Demo

err-url: https://xxx.xxx.com/static/number.ttf
The URL paths of CSS and JS files are handled correctly.
But the reference path in CSS retains only the host part of assetsPath and loses /dir.
